version: "3.9"
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=pd_aggregator
      - POSTGRES_USER=pd_aggregator
      - POSTGRES_DB=pd_aggregator

  portal:
    image: portal:latest
    container_name: portal
    build: portal
    restart: always
    links:
      - "postgres:database"
    expose:
      - 8081
    ports:
      - 8081:8081

  client:
    image: client:latest
    container_name: client
    build: client
    restart: always
    depends_on:
      - portal
    links:
      - portal
    expose:
      - 8888
    ports:
      - 8888:80

  firefox:
    image: selenium/node-firefox:latest
    container_name: firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_GRID_URL=http://localhost:4444

  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  scanner:
    image: scanner:latest
    container_name: scanner
    build: scanner
    links:
      - "postgres:database"
      - selenium-hub
    expose:
      - 8082
    ports:
      - "8082:8082"
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres-data:
