version: "3.9"
services:
  postgres:
    image: postgres:9.6
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pd_aggregator
      - POSTGRES_USER=pd_aggregator
      - POSTGRES_DB=pd_aggregator
#    restart: unless-stopped
  scanner:
    image: scanner:latest
    network_mode: bridge
    container_name: scanner
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - postgres
    links:
      - postgres
#    restart: unless-stopped
volumes:
  postgres-data: