version: "3.9"
services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=pd_aggregator
      - POSTGRES_USER=pd_aggregator
      - POSTGRES_DB=pd_aggregator

  portal:
    image: portal:latest
    container_name: portal
    build: portal
    restart: always
    links:
      - "postgres:database"
    expose:
      - 8081
    ports:
      - 8081:8081

  client:
    image: client:latest
    container_name: client
    build: client
    restart: always
    depends_on:
      - portal
    links:
      - portal
    expose:
      - 8888
    ports:
      - 8888:80

  hub:
    image: selenium/hub
    container_name: hub
    restart: always
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000

  firefox:
    image: selenium/node-firefox
    container_name: firefox
    restart: always
    depends_on:
      - hub
    environment:
      HUB_PORT_4444_TCP_ADDR: hub
      HUB_PORT_4444_TCP_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "9002:5900"
    links:
      - hub

  scanner:
    image: scanner:latest
    container_name: scanner
    build: scanner
    links:
      - "postgres:database"
      - hub
    expose:
      - 8082
    ports:
      - 8082:8082
    restart: always

volumes:
  postgres-data:
